services:
  sqlserver:
    build: ./mssql
    container_name: dockerbdfestivosqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Carlos611*"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - red

volumes:
  sqlserver_data:

networks:
  red:
    driver: bridge